FROM python:3.13-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY requirements.frontend.txt .

RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r requirements.frontend.txt

COPY frontend ./frontend
COPY app ./app

EXPOSE 8501

CMD ["streamlit", "run", "frontend/ui.py", "--server.address=0.0.0.0", "--server.port=8501"]